SET IDENTITY_INSERT [dbo].[tbl_other_member_migrations] ON
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (1, 3, 4, 1, 1, 4, 1, NULL, 1, 5, CAST(0x0000A2D8008700F0 AS DateTime), NULL, CAST(0x0000A2D8014CC2D9 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (2, 3, 4, 2, 1, 3, 1, NULL, 0, 5, CAST(0x0000A2D80087C4A4 AS DateTime), NULL, CAST(0x0000A2D8014D86BC AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (3, 5, 2, 1, 1, 1, 1, NULL, 0, 6, CAST(0x0000A2D80098F760 AS DateTime), NULL, CAST(0x0000A2D8015EB924 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (4, 18, 4, 9, 1, 6, 0, NULL, 0, 11, CAST(0x0000A2EB00496E0C AS DateTime), NULL, CAST(0x0000A2EB010F2F02 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (5, 86, 4, 9, 1, 1, 0, NULL, 0, 11, CAST(0x0000A2F3004D9040 AS DateTime), NULL, CAST(0x0000A2F301135167 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (6, 119, 4, 3, 1, 6, 0, NULL, 1, 10, CAST(0x0000A313005A0D20 AS DateTime), NULL, CAST(0x0000A313011FCE33 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (7, 153, 4, 9, 1, 6, 0, NULL, 0, 10, CAST(0x0000A3350035D414 AS DateTime), NULL, CAST(0x0000A33500FB9610 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (9, 992, 4, 1, 1, 2, 0, NULL, 0, 18, CAST(0x0000A38C003C4E48 AS DateTime), NULL, CAST(0x0000A38C01020FB6 AS DateTime))
INSERT [dbo].[tbl_other_member_migrations] ([OtherMemberMigrationID], [SaMIProfileID], [FamilyMemberID], [CountryID], [DoesSendMoney], [MoneyRangeID], [FacedProblem], [ProblemID], [VisitSameCountry], [CreatedBy], [CreatedDate], [UpdatedBy], [UpdatedDate]) VALUES (10, 1646, 4, 3, 1, 1, 0, NULL, 0, 10, CAST(0x0000A39200D33E84 AS DateTime), NULL, CAST(0x0000A39200D33F82 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_other_member_migrations] OFF